name: cd

on: [push, pull_request]

jobs:
  cd:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [16]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node env
        uses: actions/setup-node@v3.1.0
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        run: npm i

      - name: Generate
        run: npm run generate

      - name: Pushes to another repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: './dist'
          destination-github-username: 'LutherieUrbaine93'
          destination-repository-name: 'LutherieUrbaine93.github.io'
          user-email: adrientasic7@gmail.com
          target-branch: main
